Task1-2

public class Task1_2 {
    public static void main(String[] args) {
    String[] country ={"JAPAN"."AMERICA"."KOREA"};
    



    System.out.println(country.length):




String[] strArray = new String[3];
strArray[1] = "りんご";
strArray[２] = "もも";
strArray[３] = "ぶどう";
System.out.println("配列strArrayの要素数…" + strArray.length);
//int型の変数 Arrayの宣言と初期化//
int[] intArray = { 10, 20, 30, 40, 50 }:
//１。４で初期化//
System.out.println(intArray[1] + intArray[4]);

    }}


